### ISSUE TITLE
SG Imported Project - Duplicate Statuses

### ISSUE THREAD

**Issue by matteoveglia** [ynput/ayon-shotgrid#52]
Hi,

When importing a project from ShotGrid, should we be wiping out the default statuses and only use the imported ones?

I'm wondering if keeping both might cause issues in the future, for example here's an import of a Demo project from our ShotGrid which is using all our statuses and I'm seeing lots of duplicates presumably from AYON:
![image](https://github.com/ynput/ayon-shotgrid/assets/1258632/669ad9ca-0038-4fbe-9b44-8e3fc6378ed7)

Additionally, maybe it would be worth being able to specify which Anatomy Preset you want to use for a project before the import happens?

**Comment by jakubjezek001** [comment]
Hey @matteoveglia, I'm going to update the documentation for the addon bootstrap process soon to provide clear instructions. For now, the only way to fix this issue is by creating a specific anatomy preset for SG with one item in task types, folder types, and statuses. These items should match those that exist by default in SG. With the latest 0.4.0 release, we've added a new setting to choose your default anatomy preset. Select your SG preset there. Then, any new project you sync into Ayon will use this preset. It will automatically fill in all the necessary entities, task types, and statuses found in SG.
